name: soand
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dio: ^5.8.0+1
  go_router: ^15.2.3
  shared_preferences: ^2.5.3
  logger: ^2.5.0
  get_it: ^8.0.3
  gap: ^3.0.1
  shimmer: ^3.0.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  easy_localization: ^3.0.7+1
  flutter_bloc: ^9.1.1
  keyboard_dismisser: ^3.0.0
  lottie: ^3.3.1
  slide_to_act: ^2.0.2
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/auth/
    - assets/images/auth/
    - assets/animations/

  fonts:
    - family: Akatab
      fonts:
        - asset: assets/fonts/Akatab-Regular.ttf

        - asset: assets/fonts/Akatab-Medium.ttf

        - asset: assets/fonts/Akatab-SemiBold.ttf

        - asset: assets/fonts/Akatab-Bold.ttf

        - asset: assets/fonts/Akatab-ExtraBold.ttf

        - asset: assets/fonts/Akatab-Black.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
